### ISSUE TITLE
Aggiunta risorsa

### ISSUE THREAD

**Issue by villaggiobtc** [mirserena/risorsebitcoin#16]
Buongiorno,
nella lista delle risorse in italiano, proporrei di aggiungere una nuova categoria ad oggi non contemplata: quella di uffici/negozi fisici (physical store) incentrati su Bitcoin. Punti fisici sul territorio dove si fa formazione, educazione e consulenza alle persone che si vogliono avvicinare al mondo bitcoin e che preferiscono incontrare e parlare con qualcuno, e dove è prevista anche la vendita al dettaglio di libri divulgativi (categoria 2 dell'elenco) ed accessori bitcoin come hardware wallet, magliette ed altro.
In quest'ottica potrebbe rientrare "Villaggio Bitcoin" a Darfo Boario Terme (Brescia), nato nel 2021 e ad oggi il secondo ufficio/negozio fisico in Italia dopo il Comproeuro di Rovereto.
Questo il sito: https://www.villaggiobitcoin.it/

Inoltre, per le categorie 7 (servizi per le imprese) e 8 (imprese che accettano btc) proporrei di aggiungere anche i servizi proposti da Villaggio Bitcoin, dato che esistono già diverse attività commerciali convenzionate e che oggi accettano btc come modalità di pagamento!
Qui il link: https://www.villaggiobitcoin.it/chi-accetta-bitcoin/

Grazie mille a tutta la community!
Valerio
Villaggio Bitcoin

**Comment by mirserena** [comment]
Assolutamente ok con entrambe le proposte! Se aspetti me però la cosa diventa lunga, se mi mandi o fai mandare una PR con le modifiche faccio merge volentieri :) 

Di altri physical store mi viene in mente quello di inbitcoin a Rovereto... Ma solo voi 2, speriamo di vedervi crescere!
