### ISSUE TITLE
Sezione "Runnare un nodo" linak a vecchia versione di Bitcoin

### ISSUE THREAD

**Issue by BTCBellyButton** [mirserena/risorsebitcoin#9]
Il link al download di Bitcoin core porta alla vecchia versione.
L'ultima e' la v22.0.
Probabilmente manca la pagina in italiano su bitcoin.org.
Peraltro il processo di verifica delle firme e' cambiato quindi andrebbe comunque ri-tradotta e rivista.

Latest release: https://bitcoincore.org/en/download/

**Comment by mirserena** [comment]
Grazie mille! ho messo appunto sulla lista qui e segnato eventualmente di aiutare con traduzione italiana
